spring:
  application:
    name: eureka-consumer
server:
  port: 7001

# eureka服务消费者的配置
eureka:
  client:
    register-with-eureka: false       # 为了便于管理，消费者不注册为服务提供者
    service-url:    # 服务注册的请求地址
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka/

ribbon:
  secure-ports: